# Uncomment the next line to define a global platform for your project
platform :ios, '13.0' # Adjust as needed

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # Add any other pods you need for your iOS app
end
